// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizzaria.Data;

#nullable disable

namespace PizzariaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250613013649_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Pizzaria.Models.tb_cadastro_cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cep_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cidade_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("estado_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hash_senha_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("is_admin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nome_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("numero_rua_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rua_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tb_cadastro_cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
