// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizzaria.Data;

#nullable disable

namespace PizzariaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250615050735_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Pizzaria.Models.Tb_bebida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao_bebida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_alcoolica")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome_bebida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor_bebida")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Tb_bebida");
                });

            modelBuilder.Entity("Pizzaria.Models.Tb_cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cep_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash_senha_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero_rua_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rua_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tb_cliente");
                });

            modelBuilder.Entity("Pizzaria.Models.Tb_filiais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao_filial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco_Filial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome_filial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone_Filial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tb_filiais");
                });

            modelBuilder.Entity("Pizzaria.Models.Tb_pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao_pizza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_salgada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome_pizza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor_pizza")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Tb_pizza");
                });

            modelBuilder.Entity("Pizzaria.Models.Tb_sobremesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome_sobremesa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rua_cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor_sobremesa")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Tb_sobremesa");
                });
#pragma warning restore 612, 618
        }
    }
}
